version: "3.8"
services:
  neo4j:
    image: neo4j:5.12
    container_name: neo4j-graph
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_auth__enabled: "true"
      NEO4J_server_scripts_init: /var/lib/neo4j/import/init.cypher
    volumes:
      - ./import:/var/lib/neo4j/import
